//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoryMaker.Graph {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultGraph {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultGraph() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StoryMaker.Graph.DefaultGraph", typeof(DefaultGraph).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;$id&quot;: &quot;67&quot;,
        ///    &quot;NodeRelations&quot;: {
        ///      &quot;$id&quot;: &quot;68&quot;,
        ///      &quot;$values&quot;: [
        ///        {
        ///          &quot;$id&quot;: &quot;69&quot;,
        ///          &quot;LeftNode&quot;: {
        ///            &quot;$id&quot;: &quot;70&quot;,
        ///            &quot;Type&quot;: &quot;Start&quot;,
        ///            &quot;Name&quot;: &quot;نقطه شروع&quot;,
        ///            &quot;EntryGates&quot;: {
        ///              &quot;$id&quot;: &quot;71&quot;,
        ///              &quot;$values&quot;: []
        ///            },
        ///            &quot;ExitGates&quot;: {
        ///              &quot;$id&quot;: &quot;72&quot;,
        ///              &quot;$values&quot;: [
        ///                {
        ///                  &quot;Key&quot;: &quot;Start&quot;,
        ///                  &quot;Value&quot;: &quot;شروع&quot;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JSON {
            get {
                return ResourceManager.GetString("JSON", resourceCulture);
            }
        }
    }
}
